import re
import sys

def convert_data_types(line):
    line = re.sub(r'int(11)', 'NUMBER(10)', line, flags=re.IGNORECASE)
    line = re.sub(r'int', 'NUMBER', line, flags=re.IGNORECASE)
    line = re.sub(r'varchar(\d+)', r'VARCHAR2(\1 CHAR)', line, flags=re.IGNORECASE)
    line = re.sub(r'text', 'CLOB', line, flags=re.IGNORECASE)
    line = re.sub(r'mediumtext', 'CLOB', line, flags=re.IGNORECASE)
    line = re.sub(r'datetime', 'TIMESTAMP', line, flags=re.IGNORECASE)
    line = re.sub(r'date', 'DATE', line, flags=re.IGNORECASE)
    line = re.sub(r'tinyint(1)', 'NUMBER(1)', line, flags=re.IGNORECASE)
    line = re.sub(r'decimal\((.*?)\)', r'NUMBER(\1)', line, flags=re.IGNORECASE)
    return line

def main():
    source_file = 'db/academic_center_db_full_backup.sql'
    schema_output_file = 'oracle_schema.sql'
    data_output_file = 'oracle_data.sql'
    triggers_output_file = 'oracle_triggers.sql'

    try:
        with open(source_file, 'r', encoding='utf-8') as f:
            full_content = f.read()
    except FileNotFoundError:
        print(f"Error: Source file not found at {source_file}")
        sys.exit(1)

    # Remove comments and other non-essential lines
    full_content = re.sub(r'^--.*?\n', '', full_content, flags=re.MULTILINE)
    full_content = re.sub(r'^/\*!.*?\*/;\n', '', full_content, flags=re.MULTILINE)
    full_content = re.sub(r'^DROP TABLE.*? ;\n', '', full_content, flags=re.MULTILINE)
    full_content = re.sub(r'^set autocommit=0;\n', '', full_content, flags=re.MULTILINE)

    # Process Schema
    schema_sql = []
    create_table_pattern = re.compile(r'CREATE TABLE `.*?` \(.*?\) ENGINE=.*?;', re.DOTALL | re.IGNORECASE)
    for match in create_table_pattern.finditer(full_content):
        statement = match.group(0)
        statement = statement.replace('`', '"')
        statement = re.sub(r'"(\w+)"', lambda m: m.group(1).upper(), statement)
        lines = statement.split('\n')
        new_lines = []
        for line in lines:
            line = convert_data_types(line)
            line = re.sub(r'AUTO_INCREMENT', 'GENERATED BY DEFAULT AS IDENTITY', line, flags=re.IGNORECASE)
            line = re.sub(r'DEFAULT CURRENT_TIMESTAMP', 'DEFAULT SYSTIMESTAMP', line, flags=re.IGNORECASE)
            if "CONSTRAINT" in line.upper() and "FOREIGN KEY" in line.upper():
                 line = re.sub(r'ON DELETE SET NULL', '', line, flags=re.IGNORECASE)
                 line = re.sub(r'ON UPDATE CASCADE', '', line, flags=re.IGNORECASE)
            new_lines.append(line)
        statement = '\n'.join(new_lines)
        statement = re.sub(r'ENGINE=.*?;', ';', statement, flags=re.DOTALL | re.IGNORECASE)
        statement = re.sub(r'\s*KEY `.*?` \(.*? ,?`?\),?\n', '', statement, flags=re.IGNORECASE)
        schema_sql.append(statement)

    # Process Data
    data_sql = []
    # Find all data blocks between "Dumping data..." and "commit;"
    data_dump_pattern = re.compile(r'Dumping data for table `.*?`\n(.*?)\ncommit;', re.DOTALL | re.IGNORECASE)
    for block in data_dump_pattern.finditer(full_content):
        data_block = block.group(1)
        # Find individual INSERT statements within the block
        insert_pattern = re.compile(r'INSERT INTO `.*?` VALUES .*?;', re.DOTALL | re.IGNORECASE)
        for match in insert_pattern.finditer(data_block):
            statement = match.group(0)
            statement = statement.replace('`', '')
            statement = statement.replace("\"", "''")
            data_sql.append(statement)

    # Process Triggers (assuming they exist and have a clear format)
    triggers_sql = []
    trigger_pattern = re.compile(r'CREATE TRIGGER `.*?`.*?END;', re.DOTALL | re.IGNORECASE)
    for match in trigger_pattern.finditer(full_content):
        statement = match.group(0)
        statement = statement.replace('`', '')
        statement = re.sub(r'CREATE TRIGGER (.*?)', r'CREATE OR REPLACE TRIGGER \1', statement, flags=re.IGNORECASE)
        statement = re.sub(r'NEW\.(\w+)', r':NEW.\1', statement, flags=re.IGNORECASE)
        statement = re.sub(r'OLD\.(\w+)', r':OLD.\1', statement, flags=re.IGNORECASE)
        statement = statement.strip() + '\n/'
        triggers_sql.append(statement)

    # Write new files
    with open(schema_output_file, 'w', encoding='utf-8') as f:
        f.write('\n\n'.join(schema_sql))
    print(f"Successfully created {schema_output_file}")

    with open(data_output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(data_sql))
        f.write('\nCOMMIT;\n')
    print(f"Successfully created {data_output_file}")

    with open(triggers_output_file, 'w', encoding='utf-8') as f:
        f.write('\n\n'.join(triggers_sql))
    print(f"Successfully created {triggers_output_file}")

if __name__ == '__main__':
    main()