ALTER TABLE Students
ADD COLUMN PhotoURL VARCHAR(255) DEFAULT NULL;

ALTER TABLE Teachers
ADD COLUMN PhotoURL VARCHAR(255) DEFAULT NULL;

ALTER TABLE Parents
ADD COLUMN PhotoURL VARCHAR(255) DEFAULT NULL;